# .github/workflows/fetch.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'someone'
          git config --global user.email 'mailer@st8jw.onmicrosoft.com'
          git config --global credential.helper store
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/guihongwong/platinum.git tmp
          cd tmp
          git checkout nuxt
          git remote add upstream https://${{ secrets.PAT_TOKEN }}@github.com/PatchyVideo/platinum.git
          
          git fetch upstream
          git merge upstream/master
          git push origin master          
